"""add unique constraint on reviews and make campaign required

Revision ID: 8e10463aa808
Revises: 5927a1e1d7fd
Create Date: 2026-08-16 14:51:40.634678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e10463aa808'
down_revision: Union[str, Sequence[str], None] = '5927a1e1d7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_ibfk_2'), 'reviews', type_='foreignkey')
    op.alter_column('reviews', 'campaign_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uix_review_brand_influencer_campaign', 'reviews', ['brand_id', 'influencer_id', 'campaign_id'])
    op.create_foreign_key(None, 'reviews', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint('uix_review_brand_influencer_campaign', 'reviews', type_='unique')
    op.alter_column('reviews', 'campaign_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('reviews_ibfk_2'), 'reviews', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
