"""add_live_url_to_assignments

Revision ID: a1036e6aaf29
Revises: 8e10463aa808
Create Date: 2026-08-20 19:23:47.625598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1036e6aaf29'
down_revision: Union[str, Sequence[str], None] = '8e10463aa808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_assignments', sa.Column('live_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_assignments', 'live_url')
    # ### end Alembic commands ###
